In [1]:
!pip3 install numpy

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\nicol\AppData\Local\Programs\Python\Python312\Scripts\pip3.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip'


In [4]:
# Array Unidimensional (Unico Eixo) #
import numpy as np 
my_array = np.array([1, 2, 3, 4, 5]) 
print(my_array)

# forma do array # 
my_array = np.array([1, 2, 3, 4, 5])
print(my_array.shape)


[1 2 3 4 5]
(5,)


In [13]:
# Array Bidimensional (Dois Eixos) #
my_array = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]) 
print(my_array)

# forma do array # 

print(my_array.shape)


[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [10]:
# Redimensionando o Array #
a = np.arange(6).reshape((3, 2))
print(a)

# imprimindo cada posição do array #
print(my_array[0]) 
print(my_array[1]) 

[[0 1]
 [2 3]
 [4 5]]
[1 2 3 4 5]
[1 2 3 4 5]


In [14]:
# alterando o valor do array # 
my_array[0][0] = -1 
print(my_array)

[[-1  2  3  4  5]
 [ 1  2  3  4  5]]


In [23]:
# Criar Array vazio #
import numpy as np 
xd = np.empty([3,2], dtype = int) 
print(xd)

[[-1398854576         576]
 [          0           0]
 [          1           0]]


In [24]:
# Criar Array que volta apenas 0 #
my_new_array = np.zeros((5)) 
print(my_new_array)


[0. 0. 0. 0. 0.]


In [29]:
# Criar um Array com números aleatórios # 
my_random_array = np.random.random((5)) 
print(my_random_array)

# Criar um Array com números aleatórios dentro de 0 a 10 # 
a = np.floor(10*np.random.random((3,4))) 
print(a)


[0.33574611 0.26256305 0.32040628 0.03887882 0.5524298 ]
[[2. 2. 6. 2.]
 [4. 0. 8. 0.]
 [8. 9. 5. 4.]]


In [34]:
# Indexação de Array (Selecionarar um arrray ou uma sequência de arrays específicos # 
my_array2 = np.array([3, 2, 8, 22, 127]) 
print(my_array2[3]) # selecionar o 4 elemento do array #

my_array2 = np.array([3, 2, 8, 22, 127]) 
print(my_array2[1:]) # selecionar o 2 elemento do array até o último #

my_array2 = np.array([3, 2, 8, 22, 127]) 
print(my_array2[2:4]) # selecionar do 3 elemento ao 5 elemento #

22
[  2   8  22 127]
[ 8 22]


In [35]:
# selecionar um array em bidimensões #
my_array = np.array([[4, 5], [6, 1]])
print(my_array[0][1]) 


5


In [36]:
# Manipulando os valores de um Array # 
a = np.array([[1.0, 2.0], [3.0, 4.0]])
b = np.array([[5.0, 6.0], [7.0, 8.0]])

sum = a + b # Soma
difference = a - b # Subtração
product = a * b # Multiplicação por elemento #
quotient = a / b # Divisão

print('Sum = \n', + sum)
print('\n')
print('Difference = \n', + difference)
print('\n')
print('Product = \n', + product)
print('\n')
print('Quotient = \n', + quotient)

Sum = 
 [[ 6.  8.]
 [10. 12.]]


Difference = 
 [[-4. -4.]
 [-4. -4.]]


Product = 
 [[ 5. 12.]
 [21. 32.]]


Quotient = 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [37]:
# Multiplicação por array #
matrix_product = a.dot(b) 
print('Matrix Product = \n', + matrix_product)


Matrix Product = 
 [[19. 22.]
 [43. 50.]]
